version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: vc_master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vc_master
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      AWS_ACCESS_KEY_ID: to_set
      AWS_SECRET_ACCESS_KEY: to_set
      AWS_REGION: ap-south-1
      S3_BUCKET_NAME: creditapp-test
